# Generated by Django 5.1.6 on 2025-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_language_languageversion_delete_pythonversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='docker_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
