# Generated by Django 5.1.6 on 2025-05-28 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_language_docker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeexecution',
            name='language',
        ),
        migrations.AddField(
            model_name='codeexecution',
            name='language_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='execution.languageversion'),
        ),
    ]
